# Generated by Django 5.2.4 on 2025-08-01 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('item_create', 'Item Created'), ('item_edit', 'Item Edited'), ('item_delete', 'Item Deleted'), ('supplier_action', 'Supplier Action'), ('purchase', 'Purchase'), ('user_action', 'User Action')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
